        !COMPILER-GENERATED INTERFACE MODULE: Sun Feb 19 11:18:21 2017
        MODULE RANDOMFUNC__genmod
          INTERFACE 
            FUNCTION RANDOMFUNC(LBOUND,UBOUND)
              REAL(KIND=4) :: LBOUND
              REAL(KIND=4) :: UBOUND
              REAL(KIND=4) :: RANDOMFUNC
            END FUNCTION RANDOMFUNC
          END INTERFACE 
        END MODULE RANDOMFUNC__genmod
